/**
 * Real Estate Catalogue
 * Search through properties.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@tomfurrier.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Tag } from './tag';

export interface RealEstate {
  id?: string;
  isDeleted: boolean;
  /**
   * For rent or buy
   */
  intent?: RealEstate.IntentEnum;
  title: string;
  price: number;
  city: string;
  zipCode?: number;
  district?: number;
  street?: string;
  addressNum?: string;
  floorArea: number;
  lotSize?: number;
  roomCount: string;
  mediaUrls: Array<any>;
  previewMediaUrl?: any;
  newlyBuilt?: boolean;
  constructionYear?: number;
  seoKeywords?: string;
  /**
   * Real estate type
   */
  realEstateType?: RealEstate.RealEstateTypeEnum;
  description: string;
  /**
   * Real estate selling status in the catalogue
   */
  sellingStatus?: RealEstate.SellingStatusEnum;
  tags?: Array<Tag>;
}
export namespace RealEstate {
  export type IntentEnum = 'rent' | 'buy';
  export const IntentEnum = {
    Rent: 'rent' as IntentEnum,
    Buy: 'buy' as IntentEnum
  };
  export type RealEstateTypeEnum =
    | 'flat'
    | 'house'
    | 'rentedRoom'
    | 'office'
    | 'garage'
    | 'site'
    | 'summerHouse'
    | 'agriculturalArea'
    | 'soil';
  export const RealEstateTypeEnum = {
    Flat: 'flat' as RealEstateTypeEnum,
    House: 'house' as RealEstateTypeEnum,
    RentedRoom: 'rentedRoom' as RealEstateTypeEnum,
    Office: 'office' as RealEstateTypeEnum,
    Garage: 'garage' as RealEstateTypeEnum,
    Site: 'site' as RealEstateTypeEnum,
    SummerHouse: 'summerHouse' as RealEstateTypeEnum,
    AgriculturalArea: 'agriculturalArea' as RealEstateTypeEnum,
    Soil: 'soil' as RealEstateTypeEnum
  };
  export type SellingStatusEnum = 'available' | 'sold';
  export const SellingStatusEnum = {
    Available: 'available' as SellingStatusEnum,
    Sold: 'sold' as SellingStatusEnum
  };
}
