/**
 * Real Estate Catalogue
 * Search through properties.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@tomfurrier.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RealEstate } from './realEstate';
import { Tag } from './tag';


export interface RealEstateDetails extends RealEstate {
    /**
     * Real estate type
     */
    realEstateType?: RealEstateDetails.RealEstateTypeEnum;
    /**
     * Real estate selling status in the catalogue
     */
    sellingStatus?: RealEstateDetails.SellingStatusEnum;
}
export namespace RealEstateDetails {
    export type RealEstateTypeEnum = 'flat' | 'house' | 'rentedRoom' | 'office' | 'garage' | 'site' | 'summerHouse' | 'agriculturalArea' | 'soil';
    export const RealEstateTypeEnum = {
        Flat: 'flat' as RealEstateTypeEnum,
        House: 'house' as RealEstateTypeEnum,
        RentedRoom: 'rentedRoom' as RealEstateTypeEnum,
        Office: 'office' as RealEstateTypeEnum,
        Garage: 'garage' as RealEstateTypeEnum,
        Site: 'site' as RealEstateTypeEnum,
        SummerHouse: 'summerHouse' as RealEstateTypeEnum,
        AgriculturalArea: 'agriculturalArea' as RealEstateTypeEnum,
        Soil: 'soil' as RealEstateTypeEnum
    }
    export type SellingStatusEnum = 'available' | 'sold';
    export const SellingStatusEnum = {
        Available: 'available' as SellingStatusEnum,
        Sold: 'sold' as SellingStatusEnum
    }
}
