/**
 * Real Estate Catalogue
 * Search through properties.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@tomfurrier.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Tag } from './tag';


export interface RealEstate {
    id?: number;
    /**
     * For rent or buy
     */
    intent?: RealEstate.IntentEnum;
    title: string;
    price: number;
    address: string;
    floorArea: number;
    lotSize?: number;
    roomCount: string;
    photoUrls: Array<string>;
    constructionDate?: string;
    tags?: Array<Tag>;
}
export namespace RealEstate {
    export type IntentEnum = 'rent' | 'buy';
    export const IntentEnum = {
        Rent: 'rent' as IntentEnum,
        Buy: 'buy' as IntentEnum
    }
}
